platform :ios, '8.0'

inhibit_all_warnings!
install! 'cocoapods', :deterministic_uuids => false

target 'DemoProject' do
  pod 'ReactiveObjC'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'DispatchTimer'
  pod 'YYModel'
end
